before_install:
  - sudo apt-get install r-cran-tkrplot bwidget
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

language: r
cache: packages
cran: http://cran-r.c3sl.ufpr.br/
warnings_are_errors: false
r_packages:
 - roxygen2
